baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'p5.fab'
theme = 'hugo-book'

[markup.goldmark.renderer]
 unsafe = true
 footnote = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'xcode'
    tabWidth = 4




